version: "3.8"

services:
  php:
    container_name: safaa-samimiat.app
    image: "webdevops/php-apache:8.3"
    ports:
      - 8087:80
    volumes:
      - ./src:/app
    working_dir: /app

  db:
    container_name: safaa-samimiat.db
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3310:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}

networks:
  default:
    name: mynet21